{% set name = "lib-detect-testenv" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lib_detect_testenv-{{ version }}.tar.gz
  sha256: c23d5f1c8aed4ce030d977f6848ca52544b487212063d542e1ce3ec00f52ca6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - lib_detect_testenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bitranox/lib_detect_testenv
  summary: detects if pytest or doctest or pyrunner on pycharm is running
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nilchia
