{% set name = "lib-detect-testenv" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lib_detect_testenv-{{ version }}.tar.gz
  sha256: a48d3f12346aa1776f936b104d543869387c4599864e3baed99c8f3e58b2fec5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - lib_detect_testenv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bitranox/lib_detect_testenv
  summary: detects if pytest or doctest or pyrunner on pycharm is running
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nilchia
